### ISSUE TITLE
transalte missing text

### ISSUE THREAD

**Issue by Karobau40** [w20karobau40/w20karobau40.github.io#22]
currently missing:
- Projektbeschreibung
- Kontaktformular

**Comment by TobiasHeinrichIWU** [comment]
Further missing texts:

- [ ] remove annotation in Privacy 2a, change XX days to actual number
- [ ] Privacy 2b
- [ ] Do we have to rename Twitter to X in the privacy section?
- [ ] link to english versions of privacy policies in 6 and 7

**Comment by TobiasHeinrichIWU** [comment]
According to email 01.09.2023, remove Prof. Kurz from imprint?

**Comment by Karobau40** [comment]
Nutzeffekte => benefits
@TobiasHeinrichIWU
